name: "Release assets"

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  artifacts:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "Zip component dir"
        run: |
          zip -r ./custom_components.zip ./custom_components

      - name: Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: custom_components.zip
